### ISSUE TITLE
Problem with python3+ benchmarking on windows

### ISSUE THREAD

**Issue by hardbyte** [n1analytics/clkhash#58]
From the appveyor [console log ](https://ci.appveyor.com/project/hardbyte/clkhash/build/feature-appveyerci.10/job/yxvmhvd75osiuv0d):

```
============================= test session starts =============================
platform win32 -- Python 3.5.3, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
rootdir: C:\projects\clkhash, inifile:
plugins: cov-2.5.1
collected 68 items
tests\test_benchmark.py F                                                [  1%]
tests\test_bloomfilter.py ......                                         [ 10%]
tests\test_cli.py sssssssssssssssssssssssssss                            [ 50%]
tests\test_clk.py ..                                                     [ 52%]
tests\test_e2e_hashing.py ..                                             [ 55%]
tests\test_json_schema.py .                                              [ 57%]
tests\test_key_derivation.py .........                                   [ 70%]
tests\test_names.py ...                                                  [ 75%]
tests\test_schema.py ....                                                [ 80%]
tests\test_tokenizer.py ..........                                       [ 95%]
tests\test_xor_folding.py ...                                            [100%]
================================== FAILURES ===================================
____________________ TestBenchmark.test_benchmarking_hash _____________________
self = <tests.test_benchmark.TestBenchmark testMethod=test_benchmarking_hash>
    def test_benchmarking_hash(self):
>       speed = benchmark.compute_hash_speed(1000, quiet=True)
tests\test_benchmark.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
clkhash\benchmark.py:30: in compute_hash_speed
    generate_clk_from_csv(f, ('key1', 'key2'), schema, progress_bar=not quiet)
clkhash\clk.py:83: in generate_clk_from_csv
    results = generate_clks(pii_data, schema_types, key_lists, xor_folds)
clkhash\clk.py:116: in generate_clks
    results.extend(future.result())
C:\Python35\lib\concurrent\futures\_base.py:405: in result
    return self.__get_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <Future at 0x4d0f390 state=finished raised BrokenProcessPool>
    def __get_result(self):
        if self._exception:
>           raise self._exception
E           concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
C:\Python35\lib\concurrent\futures\_base.py:357: BrokenProcessPool
---------------------------- Captured stderr call -----------------------------
C:\Python35\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '0.9.0-dev' to '0.9.0.dev0'
  normalized_version,
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: no commands supplied
C:\Python35\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '0.9.0-dev' to '0.9.0.dev0'
  normalized_version,
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: no commands supplied
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python35\lib\concurrent\futures\process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "C:\Python35\lib\concurrent\futures\process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "C:\Python35\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "C:\Python35\lib\multiprocessing\queues.py", line 83, in put
    raise Full
queue.Full
=============== 1 failed, 40 passed, 27 skipped in 1.92 seconds ===============
Command exited with code 1
```

**Comment by hardbyte** [comment]
Closing as haven't seen this in 7 months and unlikely to be investigated.
